### ISSUE TITLE
Moon culminant / noon

### ISSUE THREAD

**Issue by marius-sucan** [signetica/MoonRise#5]
Hello there!

Is it possible to have it return the elevation in degrees and the moon culminant/noon time? In other words, the moon's topocentric (as seen from the observer's place on the Earth's surface) horizontal coordinates, in degrees at culminant time and, query time.

Thank you !

Best regards, Marius.

**Comment by signetica** [comment]
Hi,

The purpose of these routines is to calculate the rise and set times
efficiently so that the code can be used in small embedded systems.  Of
course many things can be added to them but then they wouldn't be as useful
for the intended purpose.

So while you are welcome to start with this code for such a project, I do
not plan to develop such a feature.

Best wishes,
Cyrus

**Comment by marius-sucan** [comment]
Thank you for the reply.

Maybe make a spin-off? ;-).

Best regards, Marius.
